global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "mlops_serving"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["serving:8000"]
        labels:
          environment: "local-compose"
          service: "credit-scoring-service"